#!/usr/bin/env bash
echo "== create bucket"

#Check if th efirst argument is provided
if [ -z "$1" ]; then
    echo "There need to be a bucket name eg. ./bucket  my-bucket-name-1015612"
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket\
 --bucket $BUCKET_NAME \
 --create-bucket-configuration="LocationConstraint=ap-south-1" \
 --query Location\
 --output text
