#!/usr/bin/env bash
echo "== delete bucket"

#Check for bucketname
if [ -z "$1" ]; then
    echo "There need to be a bucket name eg. ./bucket  my-bucket-name-1015612"
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket\
 --bucket $BUCKET_NAME \
