#!/usr/bin/env bash
echo  "==delete object"

#exit immediately if any command return a non-zero status
set -e

# check for bucket
if [ -z "$1" ]; then
    echo "There need to be a bucket name eg. ./bucket  my-bucket-name-1015612"
    exit 1
fi


BUCKET_NAME=$1

aws s3api list-objects-v2 \
 --bucket $BUCKET_NAME \
 --query Contents[].Key \
 | jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

if [ ! -s /tmp/delete_objects.json ]; then
    echo "Bucket is already empty."
else
    aws s3api delete-objects \
        --bucket "$BUCKET_NAME" \
        --delete file:///tmp/delete_objects.json
    echo "All objects deleted."
fi