#!/usr/bin/env bash
#exit immediately if any command return a non-zero status
set -e

# check for bucket
if [ -z "$1" ]; then
    echo "There need to be a bucket name eg. ./bucket  my-bucket-name-1015612"
    exit 1
fi

# check for file name prefix
if [ -z "$2" ]; then
    echo "There need to be a prefix eg. ./bucket  my-bucket-name-1015612"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# where we will store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# remove folder if it already exists
rm -rf $OUTPUT_DIR

# lets create outpur folder

mkdir -p $OUTPUT_DIR

# generate a random number
# to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1;i<=$NUM_FILES; i++)); do 
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    #Generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files