#!/usr/bin/env bash

echo "== deploy s3 bucket using cloudformation"

STAKE_NAME="cfn-s3-simple"

aws cloudformation deploy\
 --template-file template.yaml\
 --no-execute-changeset \
 --region ap-south-1\
 --stack-name $STAKE_NAME